services:
  api-service:
    build:
      context: .
      dockerfile: backend_service/api-service/Dockerfile
    container_name: api_service
    ports:
      - "8002:8002"
    depends_on:
      - auth-service
    networks:
      - network_microservice
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: backend_service/auth-service/Dockerfile
    container_name: auth_service
    ports:
      - "8001:8001"
    networks:
      - network_microservice
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    container_name: frontend
    depends_on:
      - auth-service
      - api-service
    networks:
      - network_Webapp
      - network_microservice


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - frontend
    networks:
      - network_Webapp
    restart: always

networks:
  network_Webapp:
  network_microservice: