services:
  api-service:
    build:
      context: .
      dockerfile: api-service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - auth-service
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8002:8002"
    restart: unless-stopped
