pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                cleanWs() 
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose down'
                sh 'docker-compose up --build -d'
            }
        }
    }
}
