pipeline {
    agent any
    tools {
        git 'Default'  // ชื่อ Git ที่ตั้งไว้ใน Jenkins Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose down'
                sh 'docker-compose up --build -d'
            }
        }
    }
}
